server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/identity/**
          filters:
        - id: booking_service
          uri: http://localhost:8082
          predicates:
            - Path=/booking/**
        - id: hotels_service
          uri: http://localhost:8083
          predicates:
            - Path=/hotel/**
