server:
  port: 8080
  servlet:
    context-path: /identity  # Sửa chính tả từ "indentity" thành "identity"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service  # Đổi sang PostgreSQL
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver  # Thêm driver cho PostgreSQL

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Sử dụng dialect của PostgreSQL
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: cXWgolhZuRwCyI0mQGb1UtrtIrMLbpfL7T/vjghQnPi9M7NFU6o8Mp0Vk4s/7s4T12wbuO/4LbE+/uy+JyzMeA==


